apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-backend
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort  # ClusterIP would be more secure, but the GCE ingress controller doesn't support it
  ports:
    - port: {{.Values.backend.deployment.ports.containerPort}}
  selector:
    name: {{.Chart.Name}}-backend
    tier: backend