apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-only-backend
spec:
  podSelector:
    matchLabels:
      name:  {{.Chart.Name}}-postgresql
      tier: backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: {{.Chart.Name}}-backend