apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.postgresql.auth.existingSecret}}
type: Opaque
stringData:
  {{.Values.postgresql.auth.secretKeys.userPasswordKey}}: {{.Values.secrets.db_user_password}}