apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Chart.Name}}-deny-all
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchLabels:
      app: {{.Chart.Name}}
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Deny all egress traffic (except DNS)
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
  ingress: [ ]