# Disable this network policy for Google cloud as it will not work with the way google could use their ingress
{{if ne .Values.deployment.type "gce" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Chart.Name}}-allow-ingress-only
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchExpressions:
      - key: tier
        operator: In
        values:
          - backend
          - frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{.Values.networking.ingressSelectorName}}: {{.Values.networking.ingressSelectorValue}}
{{end}}