apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Chart.Name}}-allow-ingress-only
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchExpressions:
      - key: tier
        operator: In
        values:
          - backend
          - frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              "app.kubernetes.io/instance": ingress-nginx