# The Google cloud platform has its own ingress.
# This however does not have an ingress pod running in the cluster. This means that we cannot reference the ingress pod
# in the *external.network.yaml* file and allow incoming connections from this ingress pod to the backend/frontend.
# The solution for this is now to allow all incoming connections to backend/frontend.
# Another solution could be to whitelist the IP address of the gce ingress, but we decided against this...
{{if .Values.deployment.type eq "gce"}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Chart.Name}}-gce-allow-ingress
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchExpressions:
      - key: kind
        operator: In
        values:
          - frontend
          - backend
  policyTypes:
    - Ingress
  ingress:
    - { }
{{end}}