apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Chart.Name}}-admin-binding
  namespace: {{.Release.Namespace}}
subjects:
  {{  range $user := .Values.users.admin }}
  - kind: User
    name: {{ $user }}
    apiGroup: rbac.authorization.k8s.io
    {{- end }}
roleRef:
  kind: Role
  name: {{.Chart.Name}}-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Chart.Name}}-auditor-binding
  namespace: {{.Release.Namespace}}
subjects:
  {{  range $user := .Values.users.auditor }}
  - kind: User
    name: {{ $user }}
    apiGroup: rbac.authorization.k8s.io
    {{- end }}
roleRef:
  kind: Role
  name: {{.Chart.Name}}-auditor
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notes-cluster-admin-binding
subjects:
  {{  range $user := .Values.users.clusterAdmin }}
  - kind: User
    name: {{ $user }}
    apiGroup: rbac.authorization.k8s.io
    {{- end }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
