apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Chart.Name}}-admin-binding
  namespace: {{.Release.Namespace}}
subjects:
  - kind: User
    name: tbd
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{.Chart.Name}}-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Chart.Name}}-auditor-binding
  namespace: {{.Release.Namespace}}
subjects:
  - kind: User
    name: tbd
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{.Chart.Name}}-auditor
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Chart.Name}}-cert-manager-binding
  namespace: {{.Values.certManagerNamespace}}
subjects:
  - kind: User
    name: tbd
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{.Chart.Name}}-cert-manager
  apiGroup: rbac.authorization.k8s.io
