# Only supported by hte Google Cloud Kubernetes Engine
{{if eq .Values.deployment.type "gce"}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ssl-redirect
spec:
  redirectToHttps:
    enabled: true
{{end}}


