apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
spec:
  podSelector:
    matchLabels:
      app: {{.Chart.Name}}-backend
      tier: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: {{.Chart.Name}}-postgresql
      ports:
        - port: {{.Values.postgresql.containerPorts.postgresql}}