apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-backend
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Chart.Name}}-backend
      tier: backend
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}-backend
        tier: backend
    spec:
      containers:
        - name: {{.Chart.Name}}-backend
          image: "{{.Values.backend.deployment.image.repository}}:{{.Values.backend.deployment.image.tag}}"
          imagePullPolicy: "{{.Values.backend.deployment.image.pullPolicy}}"
          env:
            - name: PRODUCTION
              value: "{{.Values.backend.deployment.env.production}}"
            - name: DB_USER
              value: "{{.Values.backend.deployment.env.dbUser}}"
            - name: DB_PASSWORD
              value: "{{.Values.backend.deployment.env.dbPassword}}"
            - name: DB_DRIVER
              value: "{{.Values.backend.deployment.env.dbDriver}}"
            - name: DB_URI
              value: "{{.Values.backend.deployment.env.dbUri}}"
            - name: SINGLE_NODE
              value: "{{.Values.backend.deployment.env.singleNode}}"
            - name: DB_NAME
              value: {{.Values.postgresql.auth.database}}

          ports:
            - containerPort: {{.Values.backend.deployment.ports.containerPort}}
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ "sh", "-c", "until nc -z my-notes-postgresql 5432; do echo waiting for postgres; sleep 1; done" ]
