apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-backend
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: {{.Chart.Name}}-backend
    tier: backend