apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-deny-egress
spec:
  podSelector:
    matchLabels:
      name: {{.Chart.Name}}-backend
      tier: backend
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              name: {{.Chart.Name}}-postgresql
    - ports:
        - port: {{.Values.postgresql.containerPorts.postgresql}}
          protocol: TCP
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP