apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Chart.Name}}-deny-all
spec:
  podSelector:
    matchLabels:
      app: {{.Chart.Name}}
  policyTypes:
    - Ingress
    - Egress
  egress: []
  ingress: []