apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.Chart.Name}}-deny-all
spec:
  podSelector:
    matchLabels:
      app: {{.Chart.Name}}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - ports:
        - port: {{.Values.postgresql.containerPorts.postgresql}}
          protocol: TCP
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
  ingress: [ ]