# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{.Chart.Name}}-postgresql
#   labels:
#     app: {{ .Chart.Name }}
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
# spec:
#   claimRef:
#     name: {{.Chart.Name}}-postgresql
#     namespace: {{.Release.Namespace}}
#   accessModes:
#     - {{ .Values.pv.accessMode }}
#   capacity:
#     storage: {{.Values.pv.size}}
#   hostPath:
#     path: {{.Values.pv.hostPath}}
#
# ---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-postgresql
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.pv.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pv.size }}