# Postgres configuration
postgresql:
  commonLabels:
    app: notes-app

  fullnameOverride: notes-app-postgresql
  primary:
    podLabels:
      name: notes-app-postgresql
    persistence:
      existingClaim: notes-app-postgresql
  auth:
    enablePostgresUser: false
    username: u_notes
    database: notes
    # name of the secret that contains the password
    existingSecret: pg-user-password
    secretKeys:
      userPasswordKey: user-password
pv:
  accessMode: ReadWriteOnce
  size: 1Gi
  # Will create it in /var/lib/docker/volumes/minikube/_data/lib/docker/volumes/
  hostPath: "postgres-data"

secrets:
  db_user_password: super_secret

deployment:
  # can be gce or minikube
  type: minikube

backend:
  deployment:
    image:
      tag: gcr.io/containerisation/containerization-backend
      pullPolicy: Always
      # red or latest
      version: latest
    configName: backend-config
    config:
      production: true
      dbUser: u_notes
      dbDriver: postgresql+aiopg
      dbHost: notes-app-postgresql
      dbPort: 5432
      singleNode: true
    ports:
      containerPort: 8000

frontend:
  deployment:
    image:
      tag: gcr.io/containerisation/containerization-frontend
      pullPolicy: Always
      # red or latest
      version: latest
    ports:
      containerPort: 80

ingress:
  host: k8.omes.app
  # k8-omes-app-tls-production | k8-omes-app-tls-staging
  tlsSecretName: k8-omes-app-tls-production

networking:
  ingressSelectorName: app.kubernetes.io/instance
  ingressSelectorValue: ingress-nginx

certManagerNamespace: cert-manager

users:
  admin:
    - tbd
  auditor:
    - tbd
  crtManager:
    - tbd