pvc:
  name: pvc-my-notes
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

postgresql:
  primary:
    persistence:
      existingClaim: pvc-my-notes
  auth:
    enablePostgresUser: false
    username: u_notes
    database: notes
    existingSecret: pg-user-password
    secretKeys:
      userPasswordKey: user-password
