pvc:
  name: pvc-my-notes
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

postgresql:
  primary:
    persistence:
      existingClaim: pvc-my-notes
  auth:
    enablePostgresUser: false
    username: u_notes
    database: notes
    existingSecret: pg-user-password
    secretKeys:
      userPasswordKey: user-password

backend:
  deployment:
    image:
      repository: containerization-backend
      tag: latest
      pullPolicy: Never
    env:
      production: true
      dbUser: u_notes
      dbPassword: super_secret
      dbDriver: postgresql+aiopg
      dbUri: my-notes-postgresql:5432
      singleNode: true
    ports:
      containerPort: 8000


