pvc:
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

postgresql:
  fullnameOverride: notes-app-postgresql
  primary:
    podLabels:
      app: notes-app-postgresql
    persistence:
      existingClaim: notes-app-postgresql
  auth:
    enablePostgresUser: false
    username: u_notes
    database: notes
    existingSecret: pg-user-password
    secretKeys:
      userPasswordKey: user-password
backend:
  deployment:
    image:
      tag: gcr.io/containerisation/containerization-backend
      pullPolicy: Always
      version: latest
      # repository: containerization-backend
      # pullPolicy: Never
    env:
      production: true
      dbUser: u_notes
      dbDriver: postgresql+aiopg
      dbHost: notes-app-postgresql
      dbPort: 5432
      singleNode: true
    ports:
      containerPort: 8000
frontend:
  deployment:
    image:
      # tag: gcr.io/containerisation/containerization-frontend
      # pullPolicy: Always
      version: latest
      tag: containerization-frontend
      pullPolicy: Never
    ports:
      containerPort: 80

