pvc:
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

postgresql:
  fullnameOverride: notes-app-postgresql
  primary:
    persistence:
      existingClaim: notes-app-postgresql
  auth:
    enablePostgresUser: false
    username: u_notes
    database: notes
    existingSecret: pg-user-password
    secretKeys:
      userPasswordKey: user-password
backend:
  deployment:
    image:
      repository: containerization-backend
      tag: latest
      pullPolicy: Never
    env:
      production: true
      dbUser: u_notes
      dbPassword: super_secret
      dbDriver: postgresql+aiopg
      dbHost: notes-app-postgresql
      dbPort: 5432
      singleNode: true
    ports:
      containerPort: 8000


